import{a as p,S as L,i as c}from"./assets/vendor-ee72e1a4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const t of o)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function i(o){const t={};return o.integrity&&(t.integrity=o.integrity),o.referrerPolicy&&(t.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?t.credentials="include":o.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(o){if(o.ep)return;o.ep=!0;const t=i(o);fetch(o.href,t)}})();const d="/goit-js-hw-12/assets/error-ed7f5b38.svg",b="https://pixabay.com",w="api/",v="44801301-54ead35aff71c3b10e6d6b08d";p.defaults.baseURL=b;function g({q:s="",page:r=1,per_page:i=15,orientationPhoto:l="horizontal",typeImage:o="photo",safesearch:t="true"}={}){return p.get(w,{params:{key:v,q:s,page:r,per_page:i,language:"en",orientationPhoto:l,typeImage:o,safesearch:t}}).then(({data:n})=>n)}const C=new L(".gallery a",{captionsData:"alt",captionDelay:250}),u=document.querySelector(".gallery");function h(s){u.innerHTML="";const r=s.map(({largeImageURL:i,webformatURL:l,tags:o,likes:t,views:n,comments:f,downloads:y})=>`<li class="gallery-item">
        <a href="${i}">
          <img src="${l}" alt="${o}" width="320" height=200" class="card-img"/>
        </a>
        <ul class="galery-item-description">
          <li>
            <p class="count-text">Likes</p>
            <p class="count">${t}</p>
          </li>
          <li>
            <p class="count-text">Views</p>
            <p class="count">${n}</p>
          </li>
          <li>
            <p class="count-text">Comments</p>
            <p class="count">${f}</p>
          </li>
          <li>
            <p class="count-text">Downloads</p>
            <p class="count">${y}</p>
          </li>
        </ul>
      </li>
      `).join("");u.insertAdjacentHTML("afterbegin",r),C.refresh()}const e={form:document.querySelector(".form"),list:document.querySelector(".gallery"),buttonLoadMore:document.querySelector('[data-action="load-more"]'),spinner:document.querySelector(".loader")};console.log(e.spinner);const a={q:"",page:1,per_page:15,maxPage:0,orientationPhoto:"horizontal",typeImage:"photo",safesearch:"true"};e.form.addEventListener("submit",M);e.buttonLoadMore.classList.add("visually-hidden");console.log(e.buttonLoadMore);async function M(s){s.preventDefault(),e.list.innerHTML="",a.page=1;const r=s.currentTarget;if(a.q=r.elements.query.value.trim(),!a.q){c.show({backgroundColor:"#ef4040",close:!1,closeOnClick:!0,progressBarColor:"white",title:"Error",titleColor:"white",position:"topRight",messageColor:"white",messageSize:"16px",message:"Sorry, there are no images matching your search query. Please try again!",icon:"icon-error.svg",iconUrl:d}),r.reset();return}console.log(a.q),e.buttonLoadMore.classList.remove("visually-hidden"),e.buttonLoadMore.disabled=!0,e.spinner.classList.remove("visually-hidden");try{const{hits:i,total:l}=await g(a);a.maxPage=Math.ceil(l/a.per_page),h(i),i.length>0&&i.length!==l?(e.buttonLoadMore.disabled=!1,e.spinner.classList.add("visually-hidden"),e.buttonLoadMore.addEventListener("click",m)):(e.buttonLoadMore.classList.add("visually-hidden"),e.spinner.classList.add("visually-hidden"),c.show({backgroundColor:"#ef4040",close:!1,closeOnClick:!0,progressBarColor:"white",title:"Error",titleColor:"white",position:"topRight",messageColor:"white",messageSize:"16px",message:"Це все, що ми маємо на цей запит!",icon:"icon-error.svg",iconUrl:d}))}catch(i){console.log(i),c.show({backgroundColor:"#ef4040",close:!1,closeOnClick:!0,progressBarColor:"white",title:"Error",titleColor:"white",position:"topRight",messageColor:"white",messageSize:"16px",message:"Схоже виникла помилка!",icon:"icon-error.svg",iconUrl:d})}finally{r.reset()}}async function m(){a.page+=1,e.buttonLoadMore.disabled=!0,e.spinner.classList.remove("visually-hidden");try{const{hits:s}=await g(a);h(s),e.spinner.classList.add("visually-hidden")}catch(s){console.log(s),e.spinner.classList.add("visually-hidden"),c.show({backgroundColor:"#ef4040",close:!1,closeOnClick:!0,progressBarColor:"white",title:"Error",titleColor:"white",position:"topRight",messageColor:"white",messageSize:"16px",message:"Sorry, there are no images matching your search query. Please try again!",icon:"icon-error.svg",iconUrl:d})}finally{e.buttonLoadMore.disabled=!1,e.spinner.classList.add("visually-hidden"),a.page===a.maxPage&&(e.buttonLoadMore.classList.add("visually-hidden"),e.buttonLoadMore.removeEventListener("click",m),c.show({backgroundColor:"#ef4040",close:!1,closeOnClick:!0,progressBarColor:"white",title:"Error",titleColor:"white",position:"topRight",messageColor:"white",messageSize:"16px",message:"Це остання сторінка з можливих!",icon:"icon-error.svg",iconUrl:d}))}}
//# sourceMappingURL=commonHelpers.js.map
